### ISSUE TITLE
TypeError: can't multiply sequence by non-int of type 'float'

### ISSUE THREAD

**Issue by SiNcSaD** [MathGaron/mean_average_precision#6]
```
/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py:1183: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  axarr = np.empty(nplots, dtype=object)
Traceback (most recent call last):
  File "mean_average_precision/example.py", line 78, in <module>
    mAP.plot()
  File "/home/user/Desktop/mean_average_precision/mean_average_precision/detection_map.py", line 183, in plot
    fig, axes = plt.subplots(nrows=grid, ncols=grid)
  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 1186, in subplots
    ax0 = fig.add_subplot(gs[0, 0], **subplot_kw)
  File "/usr/lib/python2.7/dist-packages/matplotlib/figure.py", line 1005, in add_subplot
    a = subplot_class_factory(projection_class)(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/axes/_subplots.py", line 70, in __init__
    self.update_params()
  File "/usr/lib/python2.7/dist-packages/matplotlib/axes/_subplots.py", line 114, in update_params
    return_all=True)
  File "/usr/lib/python2.7/dist-packages/matplotlib/gridspec.py", line 425, in get_position
    gridspec.get_grid_positions(fig)
  File "/usr/lib/python2.7/dist-packages/matplotlib/gridspec.py", line 105, in get_grid_positions
    cellHeights = [cellH] * nrows
TypeError: can't multiply sequence by non-int of type 'float'
```
When I have this error message, modify the following file:

File "/home/user/Desktop/mean_average_precision/mean_average_precision/detection_map.py", line 183

Original code:
```
grid = math.ceil(math.sqrt(self.n_class))
fig, axes = plt.subplots(nrows=grid, ncols=grid)
```
Should be:
```
grid = int(math.ceil(math.sqrt(self.n_class)))
fig, axes = plt.subplots(nrows=grid, ncols=grid)
```
Then, it can work.

**Comment by MathGaron** [comment]
Thank you, just pushed the update :+1:
